# AI Algorithm

Real numbers are written on an m×n board. At each step, you are allowed to change the sign of every number of a row or of a column. Prove that by a sequence of such steps, you can always make all row sums and column sums non-negative.

In [1]:
import numpy as np

## Random moves

In [2]:
class HappyBoard():
    def __init__(self, row_shape, col_shape) -> None:
        self.row_shape = row_shape
        self.col_shape = col_shape

    def create_board(self, mu, sigma):
        board = np.random.normal(loc=mu, scale=sigma, size=(self.row_shape, self.col_shape))
        self.board = board
        return board

    def calculate_row_and_col_sums(self):
        row = self.board.sum(axis=1)
        col = self.board.sum(axis=0)
        return row, col 

    def _change_sign_col(self, col_number):
        self.board[:, col_number] = self.board[:, col_number]*(-1)
        return self.board

    def _change_sign_row(self, row_number):
        self.board[row_number, :] = self.board[row_number, :]*(-1)
        return self.board

    def _define_stopping_rule(self):
        row_sums, col_sums = self.calculate_row_and_col_sums()
        stopping_rule = all(np.concatenate((row_sums, col_sums)) > 0)
        return stopping_rule

    def run_the_algorithm(self):

        stopping_rule = self._define_stopping_rule()
        counter = 0
        while not stopping_rule:
            change_row_or_col = np.random.randint(0, 2)
            if change_row_or_col:
                which_col = np.random.randint(0, self.col_shape)
                self._change_sign_col(which_col)
            else:
                which_row = np.random.randint(0, self.row_shape)
                self._change_sign_row(which_row)
            
            stopping_rule = self._define_stopping_rule()
            counter += 1
        return counter 
        

In [3]:
obj = HappyBoard(3, 4)
obj.create_board(mu=5, sigma=20)
print(obj.board)
obj.calculate_row_and_col_sums()
obj._define_stopping_rule()
obj.run_the_algorithm()

[[12.63812773 35.31972756 -2.36837988  0.66679536]
 [18.77268022 39.06526822  1.22122609 14.16903645]
 [-7.17364374 25.08860423 -8.39285289 -0.69490571]]


145

In [125]:
obj.calculate_row_and_col_sums()

(array([ 8.75870466, 47.87010483, 24.71983161,  8.11127891, 10.0901939 ]),
 array([69.8735989 , 16.33140281, 13.34511219]))

In [4]:
obj.board

array([[ 28.09813265,  -4.74640993,  -1.34330624],
       [ 18.72095478,  36.99633914,  -1.34114729],
       [-31.08053015,  -8.95375589,  45.62970705],
       [ 12.56012457,   3.90053248,  13.48895316],
       [ -3.89375276,  34.69941346, -12.12612002]])

### Food for thought
1. Apply regular search algorithm
2. Apply local search algorithm

    a. define a heuristic and apply a hill-climbing algorithm (calculate the row/col sums and take the row/col which has the least value)
    
    b. simulated annealing algorithm (randomly take the col/row). If it is a "negative" row/col, then certainly change the sign. If no, change with some probability.
    
3. Create a two-player game
4. Random move (done)
5. Compare the number of steps needed for each of the algorithm to converge
6. Do 1-5 for different shapes of the board
7. Create a small app that demonstrates the results
8. 